# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2023 Linaro

obj-y += clock-snapdragon.o
obj-$(CONFIG_TARGET_SDM845) += clock-sdm845.o
obj-$(CONFIG_TARGET_DRAGONBOARD410C) += clock-apq8016.o
obj-$(CONFIG_TARGET_DRAGONBOARD820C) += clock-apq8096.o
obj-$(CONFIG_TARGET_QCS404EVB) += clock-qcs404.o
