# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2017 Rockchip Electronics Co., Ltd

obj-y += pinctrl-snapdragon.o
obj-y += pinctrl-apq8016.o
obj-y += pinctrl-apq8096.o
obj-y += pinctrl-qcs404.o
obj-y += pinctrl-sdm845.o
